networks:
  mainNet: 
    driver: bridge
    name: mainNet
    enable_ipv6: true 
    ipam:
      config:
        - subnet: fde4:492a:fc7f::/48

services:
  ircd:
    build:
      context: .
      args:
        # Branch to use
        - BRANCH=unreal60_dev
        
        # Commit hash to checkout
        - COMMIT=30b9f66f716e69e0734620c9b356d66443de0d4d
    container_name: ircd
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    networks:
      - mainNet
    volumes:
      # Configuration
      #
      # conf <- base directory
      # conf/tls <- your TLS certificates
      # conf/cache <- for caching
      # conf/tmp <- temporary files
      # conf/logs <- logs
      - /mnt/datadisk/volumes/ircd/:/conf/
      
      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # Client-to-server access
      - "6667:6667"
      - "6697:6697"
      
      # Server-to-server peering
      - "6900:6900"
