name: "Docker"

on:
  push:
  workflow_dispatch:

env:
  GHCR_NAMESPACE: deavmi
  GHCR_REPOSITORY: unrealircd-docker
  PLATFORMS: linux/amd64,linux/arm/v8

jobs:
  Docker:
    name: Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Containers
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        if: github.ref_name == 'master' || github.event_name == 'workflow_dispatch'
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args:
            USER_UID=1000
            USER_GID=1003
            BRANCH=unreal60_dev
            COMMIT=30b9f66f716e69e0734620c9b356d66443de0d4d
          tags: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.GHCR_REPOSITORY }}:${{ github.ref_name }}
